version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: RooT1234
      MYSQL_DATABASE: moviesDB
      MYSQL_USER: user
      MYSQL_PASSWORD: RooT1234
    ports:
      - "3307:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: RooT1234
      DB_NAME: moviesDB